# Generated by Django 4.2.7 on 2024-02-15 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0001_initial'),
    ]

    operations = [
    ]
