# Generated by Django 4.2.7 on 2024-02-15 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0002_transfer_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='widget',
            options={'managed': True},
        ),
    ]
